const propiedades = [
  {
    titulo: "Casa Frente Al Mar",
    descripcion: "La casa tiene una bella vista al mar",
    habitaciones: 1,
    parqueos: 1,
    banos: 1,
    calle: "Calle Toribio Campusano",
    lat: "",
    lng: "",
    imagen: "",
    usuarioId: 1,
    categoriaId: 1,
    precioId: 1,
  },
  {
    titulo: "Apartamento Moderno en el Centro",
    descripcion:
      "Un apartamento completamente equipado en el corazón de la ciudad",
    habitaciones: 1,
    parqueos: 1,
    banos: 1,
    calle: "Avenida Principal #11",
    lat: "",
    lng: "",
    imagen: "",
    usuarioId: 1,
    categoriaId: 1,
    precioId: 1,
  },
  {
    titulo: "Villa de Lujo con Piscina",
    descripcion: "Espaciosa villa con piscina privada y jardines",
    habitaciones: 1,
    parqueos: 1,
    banos: 1,
    calle: "Calle Paraíso Tropical #11",
    lat: "",
    lng: "",
    imagen: "",
    usuarioId: 1,
    categoriaId: 1,
    precioId: 1,
  },
  {
    titulo: "Casa de Campo Acogedora",
    descripcion: "Perfecta para una escapada tranquila en la naturaleza",
    habitaciones: 1,
    parqueos: 1,
    banos: 1,
    calle: "Camino Rural Los Pinos",
    lat: "",
    lng: "",
    imagen: "",
    usuarioId: 1,
    categoriaId: 1,
    precioId: 1,
  },
  {
    titulo: "Penthouse con Vista a la Ciudad",
    descripcion: "Increíbles vistas panorámicas y acabados de lujo",
    habitaciones: 1,
    parqueos: 1,
    banos: 1,
    calle: "Torre Central #10, Piso 11",
    lat: "",
    lng: "",
    imagen: "",
    usuarioId: 1,
    categoriaId: 1,
    precioId: 1,
  },
  {
    titulo: "Cabaña en las Montañas",
    descripcion: "Encantadora cabaña rodeada de hermosos paisajes montañosos",
    habitaciones: 1,
    parqueos: 1,
    banos: 1,
    calle: "Valle Nevado #1",
    lat: "",
    lng: "",
    imagen: "",
    usuarioId: 1,
    categoriaId: 1,
    precioId: 1,
  },
];

export default propiedades;
